require('colors')
const { sum, sub, mult } = require('./operation')
console.log('CommonJS => '.rainbow)
console.log('Sum'.green)
console.log(sum(1, 2))
console.log('Sub'.red)
console.log(sub(1, 2))
console.log('Mult'.blue)
console.log(mult(9, 2))
